# global:
#   scrape_interval: 15s
# scrape_configs:
#   - job_name: 'redis'
#     static_configs:
#       - targets: ['redis:6379']
#   - job_name: 'nodejs'
#     static_configs:
#       - targets: ['app:3500']


global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9090']  # Adjust port based on Redis exporter
  - job_name: 'nodejs'
    static_configs:
      - targets: ['nodejs_app:3500']  # Adjust if needed
